### ISSUE TITLE
Miscellaneous Checklist

### ISSUE THREAD

**Issue by nasheomirro** [nasheomirro/wcalendar#3]
- [ ] change README.md
- [ ] add social links to site
- [ ] add LICENSE.md cause why not
